package com.fyp.furqan.security;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Environment;
import android.os.Bundle;
import android.util.Log;
import android.telephony.SmsManager;
import android.view.View;
import android.widget.ImageView;

import java.io.BufferedWriter;
import java.io.FileWriter;


public class Email_Activity extends Activity {
    public Mail m;
 public   String sk;
    ImageView ml ;



    /** Called when the activity is first created. */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_email_);
//Toast.makeText(getApplicationContext(),"Its Starting ",Toast.LENGTH_LONG).show();
ml= (ImageView) findViewById(R.id.imageView2);

        final SharedPreferences mpref = getSharedPreferences("ConfigDB", Activity.MODE_PRIVATE);
        final String sa=       mpref.getString("Email", "");
        Intent i = getIntent();





        try {

            String ph=mpref.getString("Phone","");
            String msg="Please do not reply to this SMS.\nSomebody attempted to unlock your phone.\n\nThis SMS is auto generated by \nAutoDroid";

            SmsManager smsManager = SmsManager.getDefault();
            smsManager.sendTextMessage(ph, null, msg, null, null);

        }
        catch (Exception e)
        {

        }

        sk= i.getExtras().getString("abc");
        Thread thread = new Thread(new Runnable(){
            @Override
            public void run() {
                try {
                    m= new Mail("beingpfk@gmail.com", "khan13101991");
                    String[] toArr = {sa};
                    m.setTo(toArr);
                    m.setFrom("beingpfk@gmail.com");
                    m.setSubject("This But Y?");
                    m.setBody("Email my picss");

//                    Toast.makeText(Email_Activity.this, sk+"", Toast.LENGTH_SHORT).show();
                   Log.d("Email",sk);
                    m.addAttachment(sk);
                    BufferedWriter mk = new BufferedWriter(new FileWriter(Environment.getExternalStorageDirectory().getAbsolutePath()+"/"+"q.txt",true));
                    mk.write("A");
                    if(m.send()) {
                        finish();

                   //     Toast.makeText(getApplicationContext(), "Email was sent successfully.", Toast.LENGTH_LONG).show();
                    } else {
                 //       Toast.makeText(getApplicationContext(), "Email was not sent.", Toast.LENGTH_LONG).show();
                        //Your code goes here}
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        thread.start();

    }
    @Override
    protected void onResume() {
        super.onResume();
    }

}
